# Generated by Django 3.0.6 on 2020-09-26 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('spoton', '0003_renamed_questionchoice_to_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='primary_text',
            field=models.CharField(default='default choice', max_length=100),
        ),
        migrations.AlterField(
            model_name='choice',
            name='secondary_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_spoton.question_set+', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(default='default question', max_length=400),
        ),
        migrations.AlterField(
            model_name='responseanswer',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_spoton.responseanswer_set+', to='contenttypes.ContentType'),
        ),
    ]
