# Generated by Django 3.1.4 on 2021-01-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoton', '0003_auto_20210103_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='name',
            field=models.CharField(default='Ben', max_length=50),
        ),
    ]
