# Generated by Django 3.1.5 on 2021-02-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoton', '0004_added_default_response_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='image_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
