# Generated by Django 3.1.5 on 2021-02-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoton', '0005_added_image_url_in_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='image_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
