# Generated by Django 3.1.5 on 2021-02-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoton', '0006_increased_image_url_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkboxquestion',
            name='multiselect',
            field=models.BooleanField(default=False),
        ),
    ]
