# Generated by Django 3.1.5 on 2021-02-07 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoton', '0007_explicit_CheckboxQuestion_checkbox_mc_boolean_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='background_color',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(16777215)]),
        ),
        migrations.AddField(
            model_name='response',
            name='emoji',
            field=models.CharField(default='😀', max_length=1),
        ),
    ]
