# Generated by Django 3.0.6 on 2020-08-15 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionchoice',
            name='text',
        ),
        migrations.AddField(
            model_name='questionchoice',
            name='primary_text',
            field=models.CharField(default='default choice', max_length=50),
        ),
        migrations.AddField(
            model_name='questionchoice',
            name='secondary_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='choiceanswer',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='quiz.QuestionChoice'),
        ),
    ]
