# Generated by Django 3.0.6 on 2020-08-16 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_added_secondary_text_to_choice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionChoice',
            new_name='Choice',
        ),
    ]
